### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary
This pull request removes duplicate table of contents from the readme.

### CODE REVIEW

**Review by SirSpidey — APPROVED** [review]
Change here is OK. 

Because VisRec is deprecated and no one can create instances, I recommend removing the links to `Visual Recognition with Core ML` and `Visual Recognition and Discovery with Core ML`

**Review by apaparazzi0329 — APPROVED** [review]
LGTM

**Comment by mediumTaj** [comment]
completed requested change, waiting for ci

**Review by SirSpidey — APPROVED** [review]
👍

**Pull request merged**
