### PR TITLE
Update Speech to Text

### PR DESCRIPTION
**Pull request by glennrfisher**
This pull request adds support for the following releases of the Speech to Text service:

- 14 July 2017
- 1 July 2017
- 22 May 2017
- 10 April 2017
- 8 March 2017

For detailed information on the changes associated with each release, please refer to the [release notes][1].

[1]: https://www.ibm.com/watson/developercloud/doc/speech-to-text/release-notes.html

### CODE REVIEW

**Comment by sccheng** [comment]
Oh!! Also, you had mentioned that you updated the STT credentials in the `Credentials.swift` file - do we need to re-encrypt that and push it up?

**Comment by glennrfisher** [comment]
Oh, great catch! Thanks, @sccheng!

I updated the readme and tried to search throughout the code for `opus`/ `Opus` and replace it with `oggOpus` / `OggOpus`, when appropriate. Hopefully I caught them all. ;)

Working on the encrypted credentials now -- I'll open a new PR in just a few minutes.

**Comment by troyibm** [comment]
@glennrfisher Can you tell me why the continuous boolean removed in RecognitionSettings?

**Comment by glennrfisher** [comment]
Hi @troyibm. We removed the `continuous` parameter from `RecognitionSettings` because it was removed from the Speech to Text service. It was actually removed with the [22 May 2017 release](https://www.ibm.com/watson/developercloud/doc/speech-to-text/release-notes.html#May2017), so the `continuous` parameter in the SDK hasn't had any effect since then.

We added some information to the [readme](https://github.com/watson-developer-cloud/swift-sdk#microphone-audio-and-compression) about how to stop the microphone by watching for `final` recognition results. This [comment](https://github.com/watson-developer-cloud/swift-sdk/issues/632#issuecomment-310065133) might also be helpful.

Personally, I would have preferred if the service didn't remove `continuous`, but only set its default value to `true` instead of `false`. It also would have been helpful if the service used versioning (like the version date used by other services, for example) to avoid breaking changes. But the release has been published, so our hands are tied.

**Pull request merged**
